package vn.kietnguyendev.translateapp.presentation.introduce

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.NavController
import vn.kietnguyendev.translateapp.presentation.CoreColors
import vn.kietnguyendev.translateapp.presentation.components.HeaderTitle
import vn.kietnguyendev.translateapp.presentation.components.NavigationHeader

const val text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum odio purus, condimentum vel nisl tristique, molestie dictum nulla. Nullam ipsum velit, laoreet id ante non, placerat rhoncus erat. Fusce at lacus dui. Nam augue massa, bibendum nec mattis sit amet, aliquet id purus. Nulla facilisi. Ut id rhoncus nulla. Curabitur elit metus, euismod ac consectetur id, mattis et nisl. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam tincidunt mattis finibus. Praesent efficitur egestas quam, ut vulputate nibh dignissim ut. Curabitur sit amet dolor et mi lacinia suscipit nec at purus. Vestibulum eget auctor leo, eu maximus ligula. Donec egestas dui orci, nec placerat est consectetur aliquet.\n" +
        "\n" +
        "In eget arcu nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc vulputate velit ac fringilla eleifend. Integer vestibulum augue sed suscipit sodales. Morbi et ligula vel libero gravida lobortis. Fusce sed neque consequat, placerat lectus nec, aliquet lacus. Sed lectus felis, porttitor eget turpis ac, malesuada viverra magna. Suspendisse porta sem quis condimentum aliquet.\n" +
        "\n" +
        "Nunc ac orci a magna viverra vehicula at feugiat massa. Proin eget orci nulla. Ut commodo, odio dapibus semper vestibulum, lorem lectus semper metus, ut feugiat felis diam et ante. Vivamus ex est, volutpat at finibus eu, tincidunt ut dolor. Pellentesque finibus dolor nec arcu rutrum vulputate. Proin vulputate augue eu porttitor semper. In gravida sodales congue. Sed vehicula malesuada turpis quis tristique. Suspendisse elit turpis, fringilla eu arcu at, mattis egestas elit. Sed leo neque, auctor nec sodales vel, vestibulum vitae magna. Interdum et malesuada fames ac ante ipsum primis in faucibus.\n" +
        "\n" +
        "Etiam eu dui dolor. Mauris eu molestie diam. Sed vitae eros egestas, dignissim dui scelerisque, sollicitudin ante. Cras finibus vulputate nibh, semper auctor nulla viverra non. Curabitur sit amet massa pulvinar, efficitur justo ut, faucibus odio. Cras et ullamcorper turpis. Duis consequat faucibus ex, et faucibus massa mattis id. Ut rhoncus a orci sed maximus. Morbi pharetra leo sed neque convallis lacinia.\n" +
        "\n" +
        "Curabitur interdum tincidunt diam, hendrerit ullamcorper magna sagittis at. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris viverra, quam id porta mattis, neque nulla consequat lorem, at gravida augue dolor a odio. Vivamus tincidunt mauris in leo sollicitudin, ut tempor enim porttitor. Morbi tempor, ipsum vel pellentesque elementum, erat ligula tincidunt urna, sed lobortis velit ex ac tortor. In hac habitasse platea dictumst. Nulla facilisi. Nunc fringilla purus semper, scelerisque magna ac, dapibus arcu. Nunc iaculis, nisi eu mattis mollis, massa felis dignissim risus, id gravida sem ligula ut ligula.\n" +
        "\n" +
        "Fusce nec tempus augue, vestibulum viverra mauris. Phasellus ac volutpat sapien, eget volutpat felis. Duis non diam lacinia, blandit sem vulputate, vestibulum dui. Aenean lectus tellus, commodo ac maximus non, euismod in enim. Phasellus at libero maximus, iaculis odio in, fermentum velit. Donec nec nisl placerat, bibendum elit non, tincidunt nibh. Integer sed tincidunt purus, eget aliquam nibh. Curabitur tristique quis tellus et suscipit. Sed pharetra elit magna, nec lacinia ante suscipit quis. Cras vitae eleifend arcu.\n" +
        "\n" +
        "Sed sit amet ipsum convallis, posuere enim in, vestibulum mauris. Vivamus consectetur maximus nisi, non finibus felis consequat ac. Suspendisse rhoncus nec ex eget facilisis. Sed aliquet elit metus, ac feugiat lorem ultricies ut. Aenean consequat nisi id ligula scelerisque, sit amet bibendum metus efficitur. Phasellus ornare turpis nec ante tempor ultrices. Vivamus vehicula interdum quam eu consectetur. Duis tempor ut libero sit amet faucibus. Suspendisse congue fringilla efficitur. Cras ut lacinia felis, non mattis felis. Quisque lacinia tempor enim non faucibus. Fusce enim quam, pellentesque vitae elit ut, tristique bibendum urna. Donec vel malesuada dolor. Aenean aliquam finibus bibendum.\n" +
        "\n" +
        "Cras libero enim, euismod nec consequat sodales, tempus non est. Donec ac varius ante. Mauris et libero in quam sagittis lacinia varius non nisi. Curabitur lectus dolor, iaculis eget libero ac, congue consequat lacus. Fusce risus quam, facilisis vitae tincidunt eget, tempus nec risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin leo nunc, imperdiet eget varius a, tincidunt vitae lacus. Vestibulum eleifend vitae velit eu fermentum. Praesent quam magna, eleifend ac elit vitae, semper laoreet libero. Integer rhoncus dolor ut aliquet convallis. Suspendisse gravida purus non ipsum malesuada egestas. Nam eu lacus non dui sagittis feugiat. Cras a ex ex.\n" +
        "\n" +
        "Aliquam in sem nec justo tempus vestibulum eget id elit. Suspendisse potenti. Cras gravida tortor massa, at sollicitudin mauris tristique a. Vestibulum non varius enim. Morbi sed ipsum finibus, fermentum nunc a, vulputate dolor. Curabitur imperdiet vel tortor euismod tempor. Vestibulum tempus justo vitae nunc rutrum, in facilisis tellus blandit. Duis eleifend, nibh a tristique egestas, nibh nisi iaculis neque, in imperdiet mi ex id elit. Ut ultrices, mi eu venenatis vehicula, erat neque facilisis massa, ac pretium odio sem ac velit. Duis quis mauris volutpat, aliquet felis quis, fringilla metus. Cras consectetur eros id arcu ultrices iaculis. Nulla fringilla nulla ligula, vitae aliquam orci gravida a. Quisque tristique tincidunt lacus. Proin quis neque vitae mauris suscipit aliquet.\n" +
        "\n" +
        "Sed ligula ipsum, sagittis eu sollicitudin quis, elementum vel felis. Integer sed posuere libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus ultricies, purus blandit porttitor aliquet, sapien elit varius sapien, et pulvinar sem ex a est. Morbi porta leo ut dui tempor scelerisque. Ut a viverra tortor. Phasellus ac lacinia orci, id egestas orci. Praesent pellentesque enim quam. Cras ut sodales nisi, in bibendum nibh. Suspendisse consectetur leo ut diam vestibulum eleifend. Duis non risus leo. Pellentesque vel felis eros.\n" +
        "\n" +
        "Ut eget purus ut tortor euismod sagittis nec vitae turpis. Proin non urna nec risus dictum suscipit sed nec enim. Praesent accumsan augue lobortis egestas vestibulum. Proin viverra sollicitudin ante, at egestas lectus euismod quis. Aenean a sapien efficitur, viverra metus eu, euismod neque. Sed sollicitudin neque nunc, sed dignissim libero venenatis vel. Donec dictum sagittis orci, interdum feugiat turpis sagittis eget. Nunc egestas diam rhoncus, tincidunt neque vitae, posuere purus. Vestibulum laoreet arcu eu libero sodales, ut commodo ex vehicula. Ut tincidunt urna sed sapien mattis, a tempus justo luctus. Morbi vitae egestas tortor, elementum facilisis libero. Vivamus cursus enim vitae nisl placerat tempor.\n" +
        "\n" +
        "Nam dictum lacinia ipsum, vel tempor mi consectetur eget. Donec et est sit amet diam sodales luctus. Vivamus blandit porta tellus, eu porttitor nibh aliquam eget. In pharetra mattis mollis. Cras tincidunt et leo vitae tincidunt. Nullam pellentesque laoreet vestibulum. Nullam in orci nec dolor fermentum malesuada. Integer consectetur, purus eu volutpat porta, urna velit pulvinar enim, quis rutrum quam ante nec nisi. Aenean sit amet volutpat felis, non consequat ligula. Sed egestas nulla id convallis ultricies. Fusce lobortis risus velit, ac suscipit nulla posuere eu. Proin fringilla purus eget congue rhoncus. Fusce eget pulvinar est. Mauris ut est molestie, auctor sapien at, iaculis magna. Sed fringilla auctor mi, nec eleifend elit blandit commodo.\n" +
        "\n" +
        "Maecenas at elit lobortis, feugiat ante condimentum, dapibus diam. In et volutpat orci. Donec justo nunc, maximus eu justo quis, suscipit pretium dui. Sed blandit urna est. Nulla tempus, neque a facilisis volutpat, lectus mi porta nibh, vitae semper arcu nunc a quam. Curabitur eu velit eu leo porta molestie eget at erat. Nam non fermentum odio. Sed sed auctor mauris, tincidunt vulputate mi. Integer rutrum ante sit amet gravida pharetra. Nunc malesuada libero tortor, ut rutrum lorem cursus eget.\n" +
        "\n" +
        "Nam tempus, orci id efficitur placerat, nunc ante porta quam, eget dictum augue tellus eget quam. Phasellus ut finibus ante. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur porttitor, tortor sed lobortis mollis, ipsum ex convallis diam, et auctor ligula mi a libero. Vestibulum tincidunt sodales egestas. Vestibulum sed lobortis eros. Nullam eu metus maximus ex auctor viverra. Nulla facilisi. Sed in tortor ornare, dictum ex non, semper magna. Sed sed metus nec sem pulvinar tempor et et mi. Nullam suscipit ex non ultrices dictum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras et feugiat nisl. Aenean aliquam augue elit, non dapibus tellus dapibus sit amet.\n" +
        "\n" +
        "Nullam consequat in dolor ut faucibus. Nam commodo eros magna, sit amet iaculis sapien bibendum in. Sed sit amet magna ac metus lobortis accumsan non vitae odio. Vivamus at luctus lacus, eget dapibus metus. Donec finibus non urna consectetur lacinia. Proin euismod faucibus odio et imperdiet. Etiam volutpat leo maximus magna semper lacinia. Suspendisse potenti. Aliquam bibendum mattis augue, vitae ultrices ex. Mauris sodales mollis ipsum, sed fringilla erat mollis at. In vel viverra tortor, consequat scelerisque tellus. Etiam eget nunc id lorem volutpat maximus id a orci. Praesent condimentum, tortor nec egestas pharetra, dui nulla aliquam ex, sit amet condimentum nibh purus sed leo. Maecenas ultricies ipsum eu neque dictum vulputate. Nunc vel commodo leo, at venenatis orci.\n" +
        "\n" +
        "Sed vitae est ut nibh accumsan feugiat sed ut lectus. Fusce blandit, lorem quis vehicula maximus, nunc lorem consequat lectus, quis vehicula nulla lorem a dui. Maecenas velit neque, fringilla id placerat quis, bibendum vitae libero. Integer sed neque id libero egestas vulputate a ac risus. Nunc placerat eros at urna vestibulum, nec vulputate velit lobortis. Duis pharetra, lectus et rutrum pulvinar, eros ante dignissim sem, vitae pellentesque lacus urna in metus. Sed quis mauris est. Morbi nec dictum ipsum. Proin id efficitur dolor. Vivamus diam turpis, congue ut sapien a, aliquet pretium lorem. Maecenas maximus ullamcorper suscipit. Etiam tempus, diam a commodo maximus, nibh ligula maximus nisi, ut sodales sem magna eu dolor.\n" +
        "\n" +
        "Nulla quis velit sit amet orci pharetra rhoncus. Nunc sit amet turpis non elit volutpat pretium vel in nisi. In hac habitasse platea dictumst. Vivamus sed tempus ipsum. Maecenas non tortor elementum magna vestibulum pellentesque eu placerat augue. Nam quis imperdiet eros, a elementum metus. Proin iaculis feugiat eros vel pulvinar. Curabitur et condimentum diam. Nam dignissim vestibulum erat imperdiet consectetur. Interdum et malesuada fames ac ante ipsum primis in faucibus.\n" +
        "\n" +
        "Morbi est sapien, suscipit id nisl ut, lobortis congue felis. Maecenas feugiat ante sem, vel aliquet turpis semper a. In vel tincidunt ligula. Phasellus eget suscipit odio. Donec dapibus purus et rutrum semper. Sed diam purus, hendrerit quis pulvinar a, lobortis ut massa. Donec eget libero interdum, iaculis leo vel, laoreet magna. Morbi non suscipit nisi, eu accumsan sem. Donec nec fringilla ante. Sed eleifend, est sit amet vulputate tempus, dui enim malesuada arcu, at pulvinar justo nisl sit amet arcu. Integer et pretium augue, sit amet eleifend odio. Mauris tincidunt quis massa non ullamcorper.\n" +
        "\n" +
        "Suspendisse nec sem sollicitudin, elementum turpis pulvinar, commodo lorem. Nunc sit amet vehicula augue, ac rhoncus sem. Nulla iaculis sodales velit, id pellentesque neque ornare vitae. Nullam tempus mi arcu, ut efficitur lacus sollicitudin at. Fusce risus arcu, aliquam a tempus vel, pulvinar in felis. Suspendisse erat nulla, tempus sollicitudin porttitor sit amet, pharetra sit amet lectus. Curabitur id tristique velit.\n" +
        "\n" +
        "Proin pulvinar nec lorem sit amet tempus. Pellentesque sit amet semper justo, vel pellentesque elit. Suspendisse ut interdum quam, ac pulvinar est. Nam sed nisi at purus varius molestie a sed ligula. Suspendisse ac massa at erat pharetra tempor. Vestibulum sollicitudin nulla ut felis porta, a rhoncus felis consequat. Nam id luctus lacus, eget vulputate tortor. Vivamus non elit quis felis sodales hendrerit non et velit. Curabitur mattis, tellus quis mattis eleifend, nisl lorem lacinia metus, sed tincidunt erat arcu eu ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec quis lobortis purus. Fusce finibus mauris eget sapien scelerisque, nec pharetra tortor viverra. Fusce vehicula massa vitae nisl dapibus, et consectetur urna varius. Aenean sollicitudin, ligula ut viverra malesuada, dui nulla rhoncus tellus, ac feugiat dolor quam at tortor. Integer lorem ipsum, sagittis nec lectus feugiat, pulvinar faucibus leo. Cras erat leo, dapibus eget elit non, faucibus congue urna."
@Composable
fun IntroduceScreen(navController: NavController) {
    NavigationHeader(navController = navController, title = { HeaderTitle(text = "Introduce") }) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .background(CoreColors.Background)
                .padding(16.dp)
                .verticalScroll(rememberScrollState())
        ) {
            Text(text = text, fontSize = 16.sp, fontWeight = FontWeight.Medium, color = CoreColors.Primary)
        }
    }
}